import Head from 'next/head'
import Navigation from "./Navigation";
import Footer from "./Footer";


export default function Layout({children}) {
    return (
        <div>
            <Head>
                <title>Weber GDL</title>
                <meta name="description" content="Generated by virtualdev.de"/>
                <link rel=" icon" href="../../public/favicon.ico"/>
            </Head>
            <Navigation/>
            <div className="my-col-class shadow mb-5 bg-light">
            {children}
            </div>
            <Footer/>
        </div>
    )
}